In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)


## Q1. Is there any difference in the data type of variables list_ and array_list?

In [5]:
# Checking the type of each variable
print("Type of list_:", type(list_))
print("Type of array_list:", type(array_list))


Type of list_: <class 'list'>
Type of array_list: <class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [8]:
print("Data types of elements in list_:")
for element in list_:
    print(f"{element} -> {type(element)}")

print("\nData types of elements in array_list:")
for element in array_list:
    print(f"{element} -> {type(element)}")


Data types of elements in list_:
1 -> <class 'str'>
2 -> <class 'str'>
3 -> <class 'str'>
4 -> <class 'str'>
5 -> <class 'str'>

Data types of elements in array_list:
1 -> <class 'numpy.str_'>
2 -> <class 'numpy.str_'>
3 -> <class 'numpy.str_'>
4 -> <class 'numpy.str_'>
5 -> <class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and array_list?

In [11]:
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for element in list_:
    print(f"{element} -> {type(element)}")

print("\nData types of elements in array_list (with dtype=int):")
for element in array_list:
    print(f"{element} -> {type(element)}")


Data types of elements in list_:
1 -> <class 'str'>
2 -> <class 'str'>
3 -> <class 'str'>
4 -> <class 'str'>
5 -> <class 'str'>

Data types of elements in array_list (with dtype=int):
1 -> <class 'numpy.int32'>
2 -> <class 'numpy.int32'>
3 -> <class 'numpy.int32'>
4 -> <class 'numpy.int32'>
5 -> <class 'numpy.int32'>


Answer:
Yes, there is a difference now. The list_ still contains strings, but array_list now contains integers, as we explicitly converted the data type.

In [13]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)


## Q4. Write a code to find the following characteristics of variable num_array:

In [16]:
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


## Q5. Write a code to create NumPy array of 3×3 matrix containing zeros only, using a NumPy array creation function.

In [19]:
zero_matrix = np.zeros((3, 3))
print("3x3 Zero Matrix:\n", zero_matrix)


3x3 Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q6. Create an identity matrix of shape (5,5) using NumPy functions.

In [22]:
identity_matrix = np.identity(5)
print("5x5 Identity Matrix:\n", identity_matrix)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
